language: r

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - R -e 'install.packages("quadprog")'
  - R -e 'install.packages("quadmod", repos="http://R-Forge.R-Project.org")'

  