language: r

sudo: required

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - R -e 'install.packages(c("quadprog", "lpSolveAPI"))'
  - svn checkout svn://scm.r-forge.r-project.org/svnroot/quadmod/
  - R CMD INSTALL quadmod/pkg

not_used:
  - R -e 'install.packages("quadmod", repos="http://R-Forge.R-Project.org")'

  